# Generated by Django 3.2.5 on 2021-08-03 08:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_articles_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
