# Generated by Django 3.2.5 on 2021-07-29 16:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
