# Generated by Django 3.2.5 on 2021-08-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description2',
            field=models.TextField(default='hello'),
        ),
    ]
